service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    MOCK_TABLE_NAME: ${self:custom.names.mockTable}

functions:
  dynamodb_troubleshoot:
    handler: src/modules/troubleshoot/dynamodb.handler
    events:
      - httpApi:
          method: '*'
          path: '/troubleshoot/dynamodb/{any+}'

custom:
  stage: ${sls:stage, self:provider.stage}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  esbuild:
    watch:
      pattern: './\*_/_.(js|ts)'
  # Custom Names to be used in each stage. 
  names:
    mockTable: ${self:custom.stage}-mock_table

resources:
  # DynamoDB
  - ${file(resources/dynamodb-tables.${sls:stage}.yml)}

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline