service: only-so-much-life-core
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    MOCK_TABLE_NAME: ${self:custom.names.mockTable}
    USER_TABLE: ${self:custom.names.userTable}

functions:
  user:
    handler: src/modules/users/main.handler
    events:
      - httpApi:
          method: '*'
          path: '/user/{any+}'
  authentication:
    handler: src/modules/authentication/main.handler
    events:
      - httpApi:
          method: '*'
          path: '/auth/{any+}'

custom:
  stage: ${sls:stage, self:provider.stage}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  esbuild:
    watch:
      pattern: './\*_/_.(js|ts)'
  # Custom Names to be used in each stage. 
  names:
    mockTable: ${sls:stage}-mock_table
    userTable: ${sls:stage}-user-table

resources:
  # DynamoDB
  - ${file(resources/dynamodb-tables.${sls:stage}.yml)}

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline