service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  recipe_customer:
    handler: src/recipes/handlers/customer.handler
    events:
      - httpApi:
          method: '*'
          path: '/recipe/{any+}'
  recipe_admin:
    handler: src/recipes/handlers/admin.handler
    events:
      - httpApi:
          method: '*'
          path: '/admin/recipe/{any+}'
plugins:
  - serverless-dynamodb-local
  - serverless-esbuild
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true