service: onlysomuch-life-core-services
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    USER_TABLE: ${self:custom.names.userTable}
    USER_POOL_ID:
      Ref: UserPool
    USER_POOL_CLIENT_ID:
      Ref: UserClient

functions:
  user:
    handler: src/modules/users/main.handler
    events:
      - httpApi:
          method: '*'
          path: '/user/{any+}'
  authentication:
    handler: src/modules/authentication/main.handler
    events:
      - httpApi:
          method: '*'
          path: '/auth/{any+}'

custom:
  stage: ${sls:stage, self:provider.stage}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  esbuild:
    watch:
      pattern: './\*_/_.(js|ts)'
  # Custom Names to be used in each stage. 
  names:
    userTable: ${sls:stage}-users-table
    userPool: ${sls:stage}-user-pool
    userPoolClient: ${sls:stage}-user-pool-client

resources:
  # DynamoDB
  - ${file(resources/dynamodb-tables.${sls:stage}.yml)}
  - ${file(resources/cognito-pool.${sls:stage}.yml)}

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline