  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.names.userPool}
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: 'role'
            Required: false
            Mutable: true
            AttributeDataType: String
          - Name: 'permissions'
            Required: false
            Mutable: true
            AttributeDataType: String
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.names.userPoolClient}
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"