Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.names.userTable}
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
        - AttributeName: isRemoved
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
        - AttributeName: isRemoved
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: activeUsers
          KeySchema:
            - AttributeName: isRemoved
              KeyType: HASH
            - AttributeName: userid
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  CycleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.names.cycleTable}
        AttributeDefinitions:
          - AttributeName: cycleId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: isActive
            AttributeType: S
        KeySchema:
          - AttributeName: cycleId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: currentUserCycles
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: activeCycles
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: isActive
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5