import { attribute, autoGeneratedHashKey, hashKey, rangeKey, table } from "@aws/dynamodb-data-mapper-annotations";
import { USER_TABLE } from "../../common/envars";

@table(USER_TABLE)
export class User {
    /**
     * User ID
     */
    @autoGeneratedHashKey()
    userid?:String;

    @attribute()
    firstName?: string;

    @attribute({
        type:'Date',
        defaultProvider: ()=>new Date()
    })
    joinedDate?:Date;

    @hashKey({
        type:'Custom',
        marshall: (a:any)=> ({S: String(a)}),
        unmarshall: (v) => (v.S === 'true'),
        defaultProvider: ()=>false
    })
    isRemoved?: boolean;
}