import { attribute, autoGeneratedHashKey, hashKey, rangeKey, table } from "@aws/dynamodb-data-mapper-annotations";
import { BaseEntity } from "../../common/common.types";
import { USER_TABLE } from "../../common/envars";
import { UserRolePermissions } from "../../common/types/UserRoles";
import { DynamodbCRUD } from "../../libs/datarepo/impl/dynamodb.crud.repo";

@table(USER_TABLE)
export class User extends BaseEntity {
    /**
     * User ID
     */
    @autoGeneratedHashKey()
    userid?: String;

    @attribute()
    email?: string;

    @attribute()
    firstName?: string;

    @attribute({
        type: "Date",
        defaultProvider: () => new Date(),
    })
    joinedDate?: Date;

    @hashKey(DynamodbCRUD.getStringToBooleanHashKeyConfig() as any)
    isRemoved?: boolean;

    @attribute()
    isEmailVerified?: boolean;

    @attribute()
    permissions?: UserRolePermissions;
}