import { BaseDto, Media, TimeBreakdown } from "../../common/common.types";
import { QuantityByServeSize, RecipeInstructionStep } from "../types/recipe.types";
import { Ingredient } from "../models/Ingredient.model";
import {
    table, 
    autoGeneratedHashKey, 
    attribute,
    rangeKey
} from '@aws/dynamodb-data-mapper-annotations';

/**
 * Mapper classes will map domain objects to Dynamodb entities.
 */

@table('recipes')
export class RecipeDBMapper  {
    @autoGeneratedHashKey()
    recipeId?: string;
    
    @attribute()
    name?: string;
    
    // @attribute()
    // description?: string;
    // @attribute()
    // instructionVideo?: Media | string;
    // @attribute()
    // ingredients?: {ingredient: Ingredient, quantity: QuantityByServeSize}[];
    // @attribute()
    // instrctions?: RecipeInstructionStep[];
    // @attribute()
    // totalPrepTime?: TimeBreakdown;
    // @attribute()
    // customerScore?: number;
    // @attribute()
    // tags?: string[];
    // @attribute()
    // mealChecks?: {
    //     isVeg: boolean;
    //     isLowCarb: boolean;
    //     isHighProtein: boolean;
    //     containsNuts: boolean;
    //     containsDairy: boolean;
    //     isHalal: boolean;
    // }
    // @attribute()
    // isAvailable?: boolean;
    // @attribute()
    // createdBy!: string;
    // @rangeKey({
    //     type: "Date",
    //     defaultProvider: () => new Date()
    // })
    // createdOn!: Date;
    // @attribute()
    // updatedBy?: string | undefined;
    // @rangeKey({
    //     type: "Date",
    //     defaultProvider: () => new Date()
    // })
    // updatedOn?: Date | undefined;
    // @attribute()
    // isRemoved?: boolean | undefined;
    // @rangeKey({
    //     type: "Date",
    //     defaultProvider: () => new Date()
    // })
    // removedOn?: Date | undefined;
    // @attribute()
    // removedBy?: string | undefined;
    // @attribute()
    // sharedWith?: { user: string; permissions: string[]; }[] | undefined;
}