import { attribute, autoGeneratedHashKey, hashKey, rangeKey, table } from "@aws/dynamodb-data-mapper-annotations";
import { BaseEntity } from "../../common/common.types";
import { CYCLE_TABLE } from "../../common/envars";
import { Sphere } from "./spheres/Sphere";
import { DynamodbCRUD } from "../../libs/datarepo/impl/dynamodb.crud.repo";

@table(CYCLE_TABLE)
export class Cycle extends BaseEntity{
    @autoGeneratedHashKey()
    public cycleId?: string;
    @hashKey({
        type:'String'
    })
    public userId?: string;
    @attribute()
    public startDate?: Date;
    @attribute()
    public duration?: number;
    
    @attribute()
    public bodySphere?: Sphere;
    @attribute()
    public mindSphere?: Sphere;
    @attribute()
    public soulSphere?: Sphere;
    @rangeKey(DynamodbCRUD.getStringToBooleanHashKeyConfig(false) as any)
    public isActive?: boolean;
}