/**
 * Mock db mapped domain object
 */

import { attribute,
        autoGeneratedHashKey,
        hashKey,
        rangeKey,
        table,
    } from "@aws/dynamodb-data-mapper-annotations";
import "reflect-metadata";

const TABLE_NAME = process.env.MOCK_TABLE_NAME || "mock_table";

@table(TABLE_NAME)
export class MockDomainModel {
    @autoGeneratedHashKey()
    id?: string;
    @rangeKey({
        type: "String",
    })
    name?: string;

    @attribute()
    age?: number;

    @hashKey({
        type: "Number",
        defaultProvider: () => 0,
    })
    isRemoved?: number;
}
