/**
 * Mock db mapped domain object
 */

import { table, 
        attribute, 
        autoGeneratedHashKey,
        rangeKey,
    } from "@aws/dynamodb-data-mapper-annotations";
import 'reflect-metadata';

@table('mock_table')
export class MockDomainModel {
    @autoGeneratedHashKey()
    id?: string;
    @rangeKey({
        type: 'String'
    })
    name?: string

    @attribute()
    age?: number;
}
